version: '3'

services:
  db:
    image: mongo
    ports:
      - 27020:27017
    volumes:
      - ./db:/data/db
    environment:
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_DATABASE: template
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  data:
    driver: local
